services:
  backend-db:
    image: "postgres:alpine"
    container_name: backend-db
    environment:
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
      - POSTGRES_DB=${BACKEND_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - backend-db-data:/var/lib/postgresql/data:delegated
  backend:
    build: 
      context: ./ 
      dockerfile: ./dockerfiles/Dockerfile.app
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend/
    env_file: .env
    restart: on-failure:5
    depends_on:
      - backend-db

volumes:
  backend-db-data:
