services:
  app-db:
    image: "postgres:alpine"
    container_name: greenhouse-db
    environment:
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data:delegated
  app:
    build: 
      context: ./ 
      dockerfile: ./dockerfiles/Dockerfile.app
    container_name: greenhouse-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    env_file: .env
    restart: on-failure:5
    depends_on:
      - app-db

volumes:
  app-db-data:
