[mypy]
# Set the Python version
python_version = 3.12
exclude = ^(install)/

# Add other mypy configuration options as needed
warn_unused_ignores = True
warn_return_any = True
warn_redundant_casts = True

# Ignore specific errors in the models folder
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated
[mypy-backend.models.*]

# Ignore specific errors in the serializers folder
[mypy-backend.serializers.*]
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated, unused-ignore

# Ignore specific errors in the views folder
[mypy-backend.views.*]
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated, unused-ignore

# Ignore specific errors in the tests folder
[mypy-backend.greenhouse.tests.*]
disable_error_code = attr-defined, type-arg



