[mypy]
# Set the Python version
python_version = 3.12
exclude = ^(install)/

# Add other mypy configuration options as needed
warn_unused_ignores = True
warn_return_any = True
warn_redundant_casts = True

# Ignore specific errors in the models folder
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated
[mypy-app.models.*]

# Ignore specific errors in the serializers folder
[mypy-app.serializers.*]
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated, unused-ignore

# Ignore specific errors in the views folder
[mypy-app.views.*]
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated, unused-ignore

# Ignore specific errors in the tests folder
[mypy-app.tests.*]
disable_error_code = misc, no-untyped-def, no-untyped-call, var-annotated, unused-ignore, assignment 

# Ignore specific errors in the tests mixins folder
[mypy-app.greenhouse.tests.commons.mixins]
disable_error_code = attr-defined



