apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greenhouse.fullname" . }}-backend-config
  labels:
    {{- include "greenhouse.labels" . | nindent 4 }}
data:
  ALLOWED_HOSTS: {{ .Values.backend.config.ALLOWED_HOSTS | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.config.CORS_ALLOWED_ORIGINS | quote }}
  CSRF_TRUSTED_ORIGINS: {{ .Values.backend.config.CSRF_TRUSTED_ORIGINS | quote }}
  CSRF_COOKIE_SECURE: {{ .Values.backend.config.CSRF_COOKIE_SECURE | quote }}
  DEBUG: {{ .Values.backend.config.DEBUG | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greenhouse.fullname" . }}-backend-nginx-config
  labels:
    {{- include "greenhouse.labels" . | nindent 4 }}
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    events {}
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile      on;
      client_body_temp_path /tmp/client_body;
      proxy_temp_path       /tmp/proxy;
      fastcgi_temp_path     /tmp/fastcgi;
      uwsgi_temp_path       /tmp/uwsgi;
      scgi_temp_path        /tmp/scgi;
      server {
        listen 9000;
        location /media/ {
          alias /backend/media/;
          expires 30d;
          add_header Cache-Control "public";
        }
        location / {
          return 404;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greenhouse.fullname" . }}-frontend-config
  labels:
    {{- include "greenhouse.labels" . | nindent 4 }}
data:
  API_URL: {{ .Values.frontend.config.API_URL | quote }}
