apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenhouse.fullname" . }}-secret
  labels:
    {{- include "greenhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secret.SECRET_KEY | quote }}
  {{- if index .Values "postgresql" "enabled" }}
  DB_HOST: {{ printf "%s-postgresql" .Release.Name | quote }}
  {{- else }}
  DB_HOST: {{ .Values.backend.secret.DB_HOST | quote }}
  {{- end }}
  DB_USER: {{ .Values.backend.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD | quote }}
  DB_NAME: {{ .Values.backend.secret.DB_NAME | quote }}
  SUPERUSER_USERNAME: {{ .Values.backend.secret.SUPERUSER_USERNAME | quote }}
  SUPERUSER_EMAIL: {{ .Values.backend.secret.SUPERUSER_EMAIL | quote }}
  SUPERUSER_PASSWORD: {{ .Values.backend.secret.SUPERUSER_PASSWORD | quote }}
