from .auth import AuthLoginTests, AuthLogoutTests
from .crops import (CropCreateApiViewTests, CropDeleteApiViewTests,
                    CropGetApiViewTests, CropImageUploadApiViewTests,
                    CropListApiViewTests, CropPartialUpdateApiViewTests,
                    CropUpdateApiViewTests)
from .planting import (PlantingCreateApiViewTests, PlantingDeleteApiViewTests,
                       PlantingGetApiViewTests, PlantingListApiViewTests,
                       PlantingPartialUpdateApiViewTests,
                       PlantingUpdateApiViewTests)
from .planting_daily_observation import (
    PlantingDailyObservationCreateApiViewTests,
    PlantingDailyObservationDetailApiViewTests,
    PlantingDailyObservationListApiViewTests)
from .planting_location import (PlantingLocationCreateApiViewTests,
                                PlantingLocationDeleteApiViewTests,
                                PlantingLocationGetApiViewTests,
                                PlantingLocationListApiViewTests,
                                PlantingLocationPartialUpdateApiViewTests,
                                PlantingLocationUpdateApiViewTests)
from .planting_location_assignment import (
    PlantingLocationAssignmentCreateApiViewTests,
    PlantingLocationAssignmentDeleteApiViewTests,
    PlantingLocationAssignmentGetApiViewTests,
    PlantingLocationAssignmentListApiViewTests,
    PlantingLocationAssignmentPartialUpdateApiViewTests,
    PlantingLocationAssignmentUpdateApiViewTests,
    PlantingLocationStatusAutoSyncTests)
from .planting_location_status import (
    PlantingLocationCurrentStatusTests,
    PlantingLocationStatusCreateApiViewTests,
    PlantingLocationStatusListApiViewTests)
from .setup import SetupAdminTests, SetupStatusTests
from .variety import (VarietyCreateApiViewTests, VarietyDeleteApiViewTests,
                      VarietyGetApiViewTests, VarietyListApiViewTests,
                      VarietyPartialUpdateApiViewTests,
                      VarietyUpdateApiViewTests)

__all__ = [
    "SetupAdminTests",
    "PlantingListApiViewTests",
    "PlantingCreateApiViewTests",
    "PlantingGetApiViewTests",
    "PlantingUpdateApiViewTests",
    "PlantingPartialUpdateApiViewTests",
    "PlantingDeleteApiViewTests",
    "SetupStatusTests",
    "AuthLoginTests",
    "AuthLogoutTests",
    "CropCreateApiViewTests",
    "CropDeleteApiViewTests",
    "CropGetApiViewTests",
    "CropListApiViewTests",
    "CropPartialUpdateApiViewTests",
    "CropUpdateApiViewTests",
    "CropImageUploadApiViewTests",
    "PlantingLocationListApiViewTests",
    "PlantingLocationCreateApiViewTests",
    "PlantingLocationGetApiViewTests",
    "PlantingLocationUpdateApiViewTests",
    "PlantingLocationPartialUpdateApiViewTests",
    "PlantingLocationDeleteApiViewTests",
    "VarietyListApiViewTests",
    "VarietyCreateApiViewTests",
    "VarietyGetApiViewTests",
    "VarietyUpdateApiViewTests",
    "VarietyPartialUpdateApiViewTests",
    "VarietyDeleteApiViewTests",
    "PlantingLocationAssignmentListApiViewTests",
    "PlantingLocationAssignmentCreateApiViewTests",
    "PlantingLocationAssignmentGetApiViewTests",
    "PlantingLocationAssignmentUpdateApiViewTests",
    "PlantingLocationAssignmentPartialUpdateApiViewTests",
    "PlantingLocationAssignmentDeleteApiViewTests",
    "PlantingLocationStatusAutoSyncTests",
    "PlantingLocationStatusListApiViewTests",
    "PlantingLocationStatusCreateApiViewTests",
    "PlantingLocationCurrentStatusTests",
    "PlantingDailyObservationListApiViewTests",
    "PlantingDailyObservationCreateApiViewTests",
    "PlantingDailyObservationDetailApiViewTests",
]
