# Generated by Django 6.0.1 on 2026-01-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0002_remove_crop_variety_crop_created_at_crop_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("NURSERYPOT", "Nursery Pot"),
                            ("POT", "Pot"),
                            ("GROUND", "Ground"),
                        ],
                        max_length=20,
                    ),
                ),
                ("height", models.DecimalField(decimal_places=2, max_digits=6)),
                ("width", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="variety",
            name="crop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="greenhouse.crop",
            ),
        ),
        migrations.CreateModel(
            name="Planting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="greenhouse.crop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantingGrowthStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("SOWING", "Sowing"),
                            ("GERMINATION", "Germination"),
                            ("TRANSPLANTING", "Transplanting"),
                            ("VEGETATIVE", "Vegetative"),
                            ("FLOWERING", "Flowering"),
                            ("FRUITING", "Fruiting"),
                            ("HARVEST", "Harvest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="stages/")),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="greenhouse.planting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantingDailyObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "leaf_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "humidity_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "light_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "soil_moisture_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "soil_ph",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "ec_ms_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "pest_pressure",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("disease_symptoms", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="observations/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_observations",
                        to="greenhouse.planting",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="greenhouse.plantinggrowthstage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantingLocationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="greenhouse.planting",
                    ),
                ),
                (
                    "planting_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="greenhouse.plantinglocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantingLocationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("DAMAGED", "Damaged"),
                            ("DESTROYED", "Destroyed"),
                            ("RETIRED", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="locations/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planting_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="greenhouse.plantinglocation",
                    ),
                ),
            ],
        ),
    ]
