# Generated by Django 6.0.1 on 2026-01-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0003_plantinglocation_alter_variety_crop_planting_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="planting",
            name="variety",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="greenhouse.variety",
            ),
        ),
    ]
