# Generated by Django 6.0.1 on 2026-01-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0004_planting_variety"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planting",
            name="variety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="greenhouse.variety",
            ),
        ),
    ]
