# Generated by Django 6.0.1 on 2026-01-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0009_alter_crop_name_alter_crop_scientific_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
