# Generated by Django 6.0.1 on 2026-02-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0011_alter_crop_max_days_to_harvest_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crop",
            options={"ordering": ["-created_at"]},
        ),
    ]
