# Generated by Django 6.0.1 on 2026-02-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0012_alter_crop_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="category",
            field=models.CharField(
                choices=[("VEGETABLE", "Vegetable"), ("FRUIT", "Fruit")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="sunlight_requirement",
            field=models.CharField(
                choices=[
                    ("FULL SUN", "Full Sun"),
                    ("PART SUN", "Part Sun"),
                    ("FULL SHADE", "Full Shade"),
                ],
                max_length=15,
            ),
        ),
    ]
