# Generated by Django 6.0.1 on 2026-04-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0018_alter_crop_image_alter_crop_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantinglocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['-created_at']},
        ),
    ]
