# Generated by Django 6.0.1 on 2026-04-16 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0019_alter_plantinglocation_options_alter_variety_options",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="variety",
            name="growth_habit",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DETERMINATE", "Determinate"),
                        ("INDETERMINATE", "Indeterminate"),
                    ],
                    max_length=15,
                )
            ),
        ),
    ]
