# Generated by Django 6.0.1 on 2026-04-20 17:18

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greenhouse", "0020_alter_variety_growth_habit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["user", "-created_at"], name="crop_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="crop_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["scientific_name"],
                name="crop_scientific_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="plantinglocation",
            index=models.Index(
                fields=["user", "-created_at"],
                name="planting_location_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plantinglocation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="planting_location_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="variety",
            index=models.Index(
                fields=["crop", "-created_at"], name="variety_crop_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variety",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="variety_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
