# Generated by Django 6.0.1 on 2026-04-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0022_rename_planting_location_user_created_idx_pl_user_created_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantinglocationstatus",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="locations/"
            ),
        ),
    ]
