# Generated by Django 6.0.1 on 2026-04-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0023_alter_plantinglocationstatus_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantinglocation",
            name="image",
        ),
    ]
