# Generated by Django 6.0.1 on 2026-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0024_remove_plantinglocation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="watered",
            field=models.BooleanField(default=False),
        ),
    ]
