# Generated by Django 6.0.1 on 2026-06-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0025_plantingdailyobservation_watered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planting',
            options={'ordering': ['-created_at']},
        ),
    ]
