# Generated by Django 6.0.1 on 2026-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0026_alter_planting_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="planting",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("HARVESTED", "Harvested"),
                    ("DEAD", "Dead"),
                    ("REMOVED", "Removed"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
