# Generated by Django 6.0.1 on 2026-07-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0027_planting_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
