# Generated by Django 6.0.1 on 2026-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0029_plantingdailyobservation_observation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="ec_ms_cm",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="height_cm",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="humidity_percent",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="leaf_count",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="light_hours",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="soil_moisture_percent",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="soil_ph",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="temperature_c",
        ),
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="rained",
            field=models.BooleanField(default=False),
        ),
    ]
