# Generated by Django 6.0.1 on 2026-08-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0030_remove_plantingdailyobservation_ec_ms_cm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="pruned",
            field=models.BooleanField(default=False),
        ),
    ]
