# Generated by Django 6.0.1 on 2026-08-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0030_remove_plantingdailyobservation_ec_ms_cm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="fertilizer_detail",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="fertilizer_type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("ORGANIC", "Organic"),
                    ("SYNTHETIC", "Synthetic"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
