# Generated by Django 6.0.1 on 2026-08-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0031_plantingdailyobservation_pruned"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="pruning_detail",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
