# Generated by Django 6.0.1 on 2026-08-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0031_plantingdailyobservation_fertilizer_detail_and_more",
        ),
        ("greenhouse", "0032_plantingdailyobservation_pruning_detail"),
    ]

    operations = []
