# Generated by Django 6.0.1 on 2026-08-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0033_merge_20260817_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="watering_event",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("WATERED", "Watered"),
                    ("RAINED", "Rained"),
                    ("SKIPPED_WET", "Soil still wet"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
