# Generated by Django 6.0.1 on 2026-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0033_merge_20260817_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="watering_event",
            field=models.CharField(
                choices=[
                    ("WATERED", "Watered"),
                    ("RAINED", "Rained (skipped watering)"),
                    ("SKIPPED_WET", "Soil still wet (skipped watering)"),
                ],
                default="SKIPPED_WET",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
