# Generated by Django 6.0.1 on 2026-08-20 01:48

from django.db import migrations


def convert_watering_fields(apps, schema_editor):
    Obs = apps.get_model("greenhouse", "PlantingDailyObservation")
    for obs in Obs.objects.all():
        if obs.watered:
            obs.watering_event = "WATERED"
        elif obs.rained:
            obs.watering_event = "RAINED"
        # else: already set to SKIPPED_WET by AddField default in 0034
        obs.save()


def reverse_watering_fields(apps, schema_editor):
    Obs = apps.get_model("greenhouse", "PlantingDailyObservation")
    for obs in Obs.objects.all():
        obs.watered = obs.watering_event == "WATERED"
        obs.rained = obs.watering_event == "RAINED"
        obs.save()


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0034_plantingdailyobservation_watering_event"),
    ]

    operations = [
        migrations.RunPython(
            convert_watering_fields,
            reverse_watering_fields,
        ),
    ]
