# Generated by Django 6.0.1 on 2026-08-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0035_convert_watering_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="rained",
        ),
        migrations.RemoveField(
            model_name="plantingdailyobservation",
            name="watered",
        ),
    ]
