# Generated by Django 6.0.1 on 2026-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0036_remove_plantingdailyobservation_rained_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="flowering_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantingdailyobservation",
            name="fruiting_started",
            field=models.BooleanField(default=False),
        ),
    ]
