# Generated by Django 6.0.1 on 2026-01-12 12:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "growth_habit",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("DETERMINATE", "Determinate"),
                                ("INDETERMINATE", "Indeterminate"),
                            ],
                            max_length=13,
                        ),
                        default=list,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("scientific_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VEGETABLE", "Vegetable"),
                            ("FRUIT", "Fruit"),
                        ],
                        default="VEGETABLE",
                        max_length=9,
                    ),
                ),
                (
                    "sunlight_requirement",
                    models.CharField(
                        choices=[
                            ("FULL SUN", "Full Sun"),
                            ("PART SUN", "Part Sun"),
                            ("FULL SHADE", "Full Shade"),
                        ],
                        max_length=10,
                    ),
                ),
                ("min_days_to_harverst", models.IntegerField()),
                ("max_days_to_harverst", models.IntegerField()),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="greenhouse.variety",
                    ),
                ),
            ],
        ),
    ]
