# Generated by Django 6.0.1 on 2026-01-14 21:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="variety",
        ),
        migrations.AddField(
            model_name="crop",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="variety",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="variety",
            name="crop",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="greenhouse.crop",
            ),
        ),
        migrations.AddField(
            model_name="variety",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="category",
            field=models.CharField(
                choices=[("VEGETABLE", "Vegetable"), ("FRUIT", "Fruit")],
                default="VEGETABLE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="sunlight_requirement",
            field=models.CharField(
                choices=[
                    ("FULL SUN", "Full Sun"),
                    ("PART SUN", "Part Sun"),
                    ("FULL SHADE", "Full Shade"),
                ],
                default="FULL SUN",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="variety",
            name="growth_habit",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DETERMINATE", "Determinate"),
                        ("INDETERMINATE", "Indeterminate"),
                    ],
                    max_length=15,
                ),
                default=list,
            ),
        ),
    ]
