# Generated by Django 6.0.1 on 2026-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_alter_planting_user_alter_plantinglocation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='max_days_to_harverst',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='min_days_to_harverst',
        ),
        migrations.AddField(
            model_name='crop',
            name='max_days_to_harvest',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_days_to_harvest',
            field=models.IntegerField(default=60),
        ),
    ]
