# Generated by Django 6.0.1 on 2026-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0008_remove_crop_max_days_to_harverst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="scientific_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
