# Generated by Django 6.0.1 on 2026-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0010_alter_crop_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='max_days_to_harvest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_days_to_harvest',
            field=models.IntegerField(),
        ),
    ]
