# Generated by Django 6.0.1 on 2026-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhouse",
            "0013_alter_crop_category_alter_crop_sunlight_requirement",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantinglocation",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plantinglocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="plantinglocation",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
