# Generated by Django 6.0.1 on 2026-02-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0015_plantinglocation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="planting_locations/"
            ),
        ),
    ]
